# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:\PROJECTS\OutsideYT\outside\views_ui\UploadTime_for_Video_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Upload_Time_for_video(object):
    def setupUi(self, Upload_Time_for_video):
        Upload_Time_for_video.setObjectName("Upload_Time_for_video")
        Upload_Time_for_video.setWindowModality(QtCore.Qt.NonModal)
        Upload_Time_for_video.resize(419, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Upload_Time_for_video.sizePolicy().hasHeightForWidth())
        Upload_Time_for_video.setSizePolicy(sizePolicy)
        Upload_Time_for_video.setMaximumSize(QtCore.QSize(600, 200))
        Upload_Time_for_video.setStyleSheet("background-color: rgb(39, 39, 39);\n"
"color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(39, 39, 39);\n"
"selection-background-color: rgb(15, 15, 15);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Upload_Time_for_video)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Video_label = QtWidgets.QLabel(Upload_Time_for_video)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Video_label.setFont(font)
        self.Video_label.setText("")
        self.Video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Video_label.setObjectName("Video_label")
        self.verticalLayout.addWidget(self.Video_label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_Day = QtWidgets.QLabel(Upload_Time_for_video)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_Day.setFont(font)
        self.label_Day.setObjectName("label_Day")
        self.gridLayout.addWidget(self.label_Day, 0, 1, 1, 1)
        self.Time = QtWidgets.QTimeEdit(Upload_Time_for_video)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Time.setFont(font)
        self.Time.setObjectName("Time")
        self.gridLayout.addWidget(self.Time, 3, 1, 1, 1)
        self.Day = QtWidgets.QDateEdit(Upload_Time_for_video)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Day.setFont(font)
        self.Day.setCalendarPopup(True)
        self.Day.setObjectName("Day")
        self.gridLayout.addWidget(self.Day, 1, 1, 1, 1)
        self.label_Time = QtWidgets.QLabel(Upload_Time_for_video)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_Time.setFont(font)
        self.label_Time.setObjectName("label_Time")
        self.gridLayout.addWidget(self.label_Time, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Upload_Time_for_video)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Upload_Time_for_video)
        self.buttonBox.accepted.connect(Upload_Time_for_video.accept) # type: ignore
        self.buttonBox.rejected.connect(Upload_Time_for_video.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Upload_Time_for_video)

    def retranslateUi(self, Upload_Time_for_video):
        _translate = QtCore.QCoreApplication.translate
        Upload_Time_for_video.setWindowTitle(_translate("Upload_Time_for_video", "Upload Time"))
        self.label_Day.setText(_translate("Upload_Time_for_video", "Day"))
        self.label_Time.setText(_translate("Upload_Time_for_video", "Time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Upload_Time_for_video = QtWidgets.QDialog()
    ui = Ui_Upload_Time_for_video()
    ui.setupUi(Upload_Time_for_video)
    Upload_Time_for_video.show()
    sys.exit(app.exec_())
