# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:\PROJECTS\OutsideYT\outside\views_ui\WatchersList_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WatchersList_Dialog(object):
    def setupUi(self, WatchersList_Dialog):
        WatchersList_Dialog.setObjectName("WatchersList_Dialog")
        WatchersList_Dialog.resize(650, 299)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WatchersList_Dialog.sizePolicy().hasHeightForWidth())
        WatchersList_Dialog.setSizePolicy(sizePolicy)
        WatchersList_Dialog.setMinimumSize(QtCore.QSize(400, 200))
        WatchersList_Dialog.setMaximumSize(QtCore.QSize(1000, 600))
        WatchersList_Dialog.setBaseSize(QtCore.QSize(500, 250))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        WatchersList_Dialog.setFont(font)
        WatchersList_Dialog.setStyleSheet("background-color: rgb(39, 39, 39);\n"
"color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(39, 39, 39);\n"
"selection-background-color: rgb(15, 15, 15);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WatchersList_Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addUser_Button = QtWidgets.QPushButton(WatchersList_Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.addUser_Button.setFont(font)
        self.addUser_Button.setStyleSheet("color: rgb(255, 255, 255);")
        self.addUser_Button.setObjectName("addUser_Button")
        self.horizontalLayout.addWidget(self.addUser_Button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.EditGroups_Button = QtWidgets.QPushButton(WatchersList_Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.EditGroups_Button.setFont(font)
        self.EditGroups_Button.setObjectName("EditGroups_Button")
        self.horizontalLayout.addWidget(self.EditGroups_Button)
        self.label = QtWidgets.QLabel(WatchersList_Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Group_comboBox = QtWidgets.QComboBox(WatchersList_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group_comboBox.sizePolicy().hasHeightForWidth())
        self.Group_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Group_comboBox.setFont(font)
        self.Group_comboBox.setObjectName("Group_comboBox")
        self.horizontalLayout.addWidget(self.Group_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Users_Table = QtWidgets.QTableView(WatchersList_Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Users_Table.setFont(font)
        self.Users_Table.setObjectName("Users_Table")
        self.verticalLayout.addWidget(self.Users_Table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CheckCookies_Button = QtWidgets.QPushButton(WatchersList_Dialog)
        self.CheckCookies_Button.setObjectName("CheckCookies_Button")
        self.horizontalLayout_2.addWidget(self.CheckCookies_Button)
        self.buttonBox = QtWidgets.QDialogButtonBox(WatchersList_Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.buttonBox.setFont(font)
        self.buttonBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(WatchersList_Dialog)
        self.buttonBox.accepted.connect(WatchersList_Dialog.accept) # type: ignore
        self.buttonBox.accepted.connect(WatchersList_Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WatchersList_Dialog)

    def retranslateUi(self, WatchersList_Dialog):
        _translate = QtCore.QCoreApplication.translate
        WatchersList_Dialog.setWindowTitle(_translate("WatchersList_Dialog", "Users List"))
        self.addUser_Button.setText(_translate("WatchersList_Dialog", " Add User "))
        self.EditGroups_Button.setText(_translate("WatchersList_Dialog", "  Edit Groups  "))
        self.label.setText(_translate("WatchersList_Dialog", "Default:"))
        self.CheckCookies_Button.setText(_translate("WatchersList_Dialog", " Check Cookies "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WatchersList_Dialog = QtWidgets.QDialog()
    ui = Ui_WatchersList_Dialog()
    ui.setupUi(WatchersList_Dialog)
    WatchersList_Dialog.show()
    sys.exit(app.exec_())
